services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    command: npm run dev
    container_name: chat-client-dev
    env_file:
      - ./client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next
    networks:
      - app-network

networks:
  app-network:
    name: chatnet
    driver: bridge
